### ISSUE TITLE
Renamed file is not picked up by createdeltapackage

### ISSUE THREAD

**Issue by pramodgavade** [jfgarcia268/vlocity-es_devops_tools#40]
We renamed a custom field from **force-app/main/default/objects/Lead/fields/NoApi_ManualUpload__c.field-meta.xml** to **force-app/main/default/objects/Lead/fields/No_Api_Manual_Upload__c.field-meta.xml**. It wasn't picked up by createdeltapackage command.

**Comment by 92SGupta** [comment]
@pramodgavade We will be releasing the new version of the tool to fix this issue.
